noteList = [
    {'pos': 2, 'timeTick': 0.4}, 
    {'pos': 3, 'timeTick': 0.4}, 
    {'pos': 4, 'timeTick': 0.4},
    {'pos': 1, 'timeTick': 0.4},
    {'pos': 1, 'timeTick': 0.5}, 
    {'pos': 2, 'timeTick': 0.8}, 
    {'pos': 3, 'timeTick': 0.8}, 
    {'pos': 4, 'timeTick': 0.8},
    {'pos': 3, 'timeTick': 1.2}, 
    {'pos': 4, 'timeTick': 1.2},
    {'pos': 1, 'timeTick': 1.2}, 
    {'pos': 1, 'timeTick': 2},
    {'pos': 2, 'timeTick': 2},
    {'pos': 3, 'timeTick': 2},
    {'pos': 4, 'timeTick': 2}, 
    {'pos': 1, 'timeTick': 3},
    {'pos': 2, 'timeTick': 3},
    {'pos': 3, 'timeTick': 3},
    {'pos': 4, 'timeTick': 3},
]